disabled_rules:
  - identifier_name
  - nesting
  - implicit_return
  - function_parameter_count
  - weak_delegate
opt_in_rules:
  - empty_count
  - implicit_return
  - nimble_operator
  - operator_usage_whitespace
  - unneeded_parentheses_in_closure_argument
  - literal_expression_end_indentation
  - closure_spacing
  - closure_end_indentation
  - force_unwrapping
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

cyclomatic_complexity:
  ignores_case_statements: true

force_cast: warning
force_try:
  severity: warning

line_length:
  warning: 150
  error: 160
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 1000
  error: 1200

function_body_length:
  warning: 50
  error: 100

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
