#!/bin/bash

# Cloning repo wiki
git clone git@github.com:salemove/ios-sdk-widgets.wiki.git /tmp/wiki

# Populating sidebar
set -euf -o pipefail

cd docs

REPLACE_PATH=`echo $(pwd)/replace.txt`
rm __Sidebar.md || true
cp __Sidebar-bkp __Sidebar.md
> $REPLACE_PATH

for DIR in $(find . -name '*.md' ! -name '*Sidebar*' -exec dirname {} \; | sort -u)
do
  if [ "$DIR" != "." ]
  then
    echo "**$(basename $DIR)**" >> replace.txt
    pushd $DIR
  fi

  > dir_sorted.txt
  > dir_replace.txt

  for FILE in $( find . -maxdepth 1 -name '*.md' ! -name '*Sidebar*' \
    -exec grep -l "# " {} \;
  )
  do
    echo $(grep -oE '\[order\]: \# (.*)' $FILE | tr -d '[order]: # ()') \
     $(grep -oE '^# .*$' $FILE | awk -v f=$FILE '{
      sub(/^# /,"")
      link = tolower(f)
      gsub(".md", "", link)
      gsub(/[^a-zA-Z0-9 _-]/, "", link)
      gsub(" ", "-", link)
      entry = "- ["$0"]("link")  "
      print entry
    }') >> "dir_replace.txt"
  done
  sort -n -o dir_sorted.txt dir_replace.txt
  sed -i '' -E 's/^[0-9]+ -/-/g' dir_sorted.txt

  printf '%s\n\n' "$(cat dir_sorted.txt)" >> $REPLACE_PATH

  rm dir_sorted.txt
  rm dir_replace.txt

  if [ "$DIR" != "." ]
  then
    popd
  fi
done

perl -pi -e 's/{{SIDEBAR_GENERATE}}/`cat replace.txt`/e' __Sidebar.md
rm replace.txt

# Adding new doc files
cp -r /tmp/wiki/.git ./
git config user.email "$GIT_CLONE_COMMIT_AUTHOR_EMAIL"
git config user.name "$GIT_CLONE_COMMIT_AUTHOR_NAME"
git add .
git commit -m "$GIT_CLONE_COMMIT_MESSAGE_SUBJECT" || changes=none

# Pushing to repo
git push
